 REGIONNAME_FINAL, '||
                          'IS_CAPITAL_INSURANCE, '||
                          'CATEGORY_ID_FINAL, '||
                          'CATEGORY_ID_2020_FINAL, '||
                          'ARM_EKIS_CONTRACTOPTION, '||
                          'ARM_EKIS_PRODUCT_PROGRAM_TYPE, '||
                          'ARM_EKIS_OBJECTCLASS, '||
                          'COVERAGES, '||
                          'SALECHANNELFULLNAME_DE, '||
                          'IS_TOTAL_LOSS, '||
                          'IS_THEFT, '||
                          'D1_MONTH, '||
                          'ACCIDENT_MONTH ';
