SELECT 
        "Месяц начала",
        "Месяц",
        "Канал продаж",
        "Флаг Е-ОСАГО",
        IS_POLICY_FROM_EA,
        IS_POLICY_FROM_E_GARANT,
        "Передан в пул?",
        CASE WHEN IS_POLICY_FROM_EA = '1' OR IS_POLICY_FROM_E_GARANT = '1' THEN '1' ELSE '0' END as drums_rca,
        "Флаг Токс_регион",
        "Регион",
        "Регион ОФР",
        "Регион крупный",
        "Признак договора",
        "Признак пролонгации",
        "Тип страхователя",
        "Заработанная премия",
        "Экспозиция",
        "Начисленная премия",
        "Количество договоров",
        "Количество полисолет",
        NULL::text as claim_type_big,
        NULL::numeric as loss_count,
        NULL::numeric as loss_sum,
        'premium' as data_source
    FROM actuary.rep_osago_ep_expo
    WHERE left("Месяц", 4)::int >= 2019
union all
    SELECT 
        "Месяц начала",
        "Месяц события",
        "Канал продаж",
        "Флаг Е-ОСАГО",
        IS_POLICY_FROM_EA,
        IS_POLICY_FROM_E_GARANT,
        "Передан в пул?",
        CASE WHEN IS_POLICY_FROM_EA = '1' OR IS_POLICY_FROM_E_GARANT = '1' THEN '1' ELSE '0' END as drums_rca,
        "Флаг Токс_регион",
        "Регион",
        "Регион ОФР",
        "Регион крупный",
        "Признак договора",
        "Признак пролонгации",
        "Тип страхователя",
        NULL::numeric as "Заработанная премия",
        NULL::numeric as "Экспозиция",
        NULL::numeric as "Начисленная премия",
        NULL::numeric as "Количество договоров",
        NULL::numeric as "Количество полисолет",
        "Тип убытка крупный",
        "Количество_убытков",
        "Сумма_убытков",
        'loss' as data_source
    FROM actuary.rep_osago_triangle
    WHERE left("Месяц события", 4)::int >= 2019
